import { renderLayout } from "../../../utils/layout";

export const LayoutDragBuilderEdit = ({
    layout,
    dashboardId,
    parentKey,
    debugMode,
    previewMode,
    editMode,
    onClickAdd,
    onClickQuickAdd,
    onDropItem,
    onDragItem,
    onClickRemove,
    onClickShrink,
    onClickExpand,
    onClickEmptyCell,
    onClickContextSettings,
    onSelectWidgetForCell,
    onChangeDirection,
    onChangeOrder,
    onOpenConfig,
    onOpenEvents,
    onSaveConfiguration,
    onProviderSelect = null,
    onCreateProvider = null,
    providers = [],
    workspace,
    isDraggable = true,
    // Grid operation handlers
    onSplitCell = null,
    onMergeCells = null,
    onAddGridRow = null,
    onDeleteGridRow = null,
    onAddGridColumn = null,
    onDeleteGridColumn = null,
    onChangeRowHeight = null,
    onMoveWidgetToCell = null,
    onDropWidgetFromSidebar = null,
}) => {
    // DndProvider is supplied by DashboardStage — no local provider needed.
    return renderLayout({
        dashboardId,
        layout,
        parentKey,
        debugMode,
        previewMode,
        onClickAdd,
        onClickQuickAdd,
        onClickRemove,
        onClickShrink,
        onClickExpand,
        onClickEmptyCell,
        onClickContextSettings,
        onSelectWidgetForCell,
        onChangeDirection,
        onChangeOrder,
        onOpenConfig,
        onOpenEvents,
        onSaveConfiguration,
        onProviderSelect,
        onCreateProvider,
        providers,
        onDropItem,
        onDragItem,
        workspace,
        editMode,
        onSplitCell,
        onMergeCells,
        onAddGridRow,
        onDeleteGridRow,
        onAddGridColumn,
        onDeleteGridColumn,
        onChangeRowHeight,
        onMoveWidgetToCell,
        onDropWidgetFromSidebar,
    });
};
