import { renderLayout } from "../../../utils/layout";
import { DndProvider } from "react-dnd";
import { HTML5Backend } from "react-dnd-html5-backend";

export const LayoutDragBuilder = ({
    layout,
    dashboardId,
    parentKey,
    debugMode,
    previewMode,
    onClickAdd,
    onClickQuickAdd,
    onDropItem,
    onClickRemove,
    onClickShrink,
    onClickExpand,
    onClickEmptyCell,
    onChangeDirection,
    onChangeOrder,
    onOpenConfig,
    onOpenEvents,
    onSaveConfiguration,
    onProviderSelect = null,
    onCreateProvider = null,
    workspace,
    isDraggable = true,
    // Grid operation handlers
    onSplitCell = null,
    onMergeCells = null,
    onAddGridRow = null,
    onDeleteGridRow = null,
    onAddGridColumn = null,
    onDeleteGridColumn = null,
    onChangeRowHeight = null,
}) => {
    return isDraggable === true ? (
        <DndProvider backend={HTML5Backend} key={"dnd-provider"}>
            {renderLayout({
                dashboardId,
                layout,
                parentKey,
                debugMode,
                previewMode,
                onClickAdd,
                onClickQuickAdd,
                onClickRemove,
                onClickShrink,
                onClickExpand,
                onClickEmptyCell,
                onChangeDirection,
                onChangeOrder,
                onOpenConfig,
                onOpenEvents,
                onSaveConfiguration,
                onProviderSelect,
                onCreateProvider,
                onDropItem,
                workspace,
                onSplitCell,
                onMergeCells,
                onAddGridRow,
                onDeleteGridRow,
                onAddGridColumn,
                onDeleteGridColumn,
                onChangeRowHeight,
            })}
        </DndProvider>
    ) : (
        renderLayout({
            dashboardId,
            layout,
            parentKey,
            debugMode,
            previewMode,
            onClickAdd,
            onClickQuickAdd,
            onClickRemove,
            onClickShrink,
            onClickExpand,
            onClickEmptyCell,
            onChangeDirection,
            onChangeOrder,
            onOpenConfig,
            onOpenEvents,
            onSaveConfiguration,
            onProviderSelect,
            onCreateProvider,
            onDropItem,
            workspace,
            onSplitCell,
            onMergeCells,
            onAddGridRow,
            onDeleteGridRow,
            onAddGridColumn,
            onDeleteGridColumn,
            onChangeRowHeight,
        })
    );
};
